const localCards = [{
        rus: "Робко",
        eng: "Humbly",
        sentenceRus: "Я не знала, прости, сказала Полли робко",
        sentenceEng: "I didn’t know. I’m sorry, said Polly humbly.",
        audio: null,
    }, {
        rus: "Напрасно",
        eng: "In vain",
        sentenceRus: "...это только вызвало бы у тебя слюноотделение напрасно",
        sentenceEng: "...it would only make your mouth water in vain.",
        audio: null,
    }, {
        rus: "Карабкаться",
        eng: "Scramble",
        sentenceRus: "Однажды утром она была у себя в саду, когда мальчик вскарабкался на ее забор",
        sentenceEng: "One morning she was out in the back garden when a boy scrambled up from the garden next door",
        audio: null,
    }, {
        rus: "Привлекательный",
        eng: "Attractive",
        sentenceRus: "...особенно, осмелюсь сказать, с такой привлекательной юной леди, как вы",
        sentenceEng: "...especially, if I may say so, such a very attractive young lady as yourself ",
        audio: null,
    },
    {
        rus: "Возможность",
        eng: "Opportunity",
        sentenceRus: "Это слишком хорошая возможность, чтобы ее упустить",
        sentenceEng: "This is too good an opportunity to miss",
        audio: null,
    },
    {
        rus: "Слабый",
        eng: "Faint",
        sentenceRus: "Слышался слабый, очень-очень слабый гудящий звук",
        sentenceEng: "There was a faint—a very, very faint—humming sound",
        audio: null,
    },
    {
        rus: "Ручка",
        eng: "Handle",
        sentenceRus: "На этой стороне не было ни засова, ни ручки",
        sentenceEng: "There was no bolt or handle on this side of it ",
        audio: null,
    },
    {
        rus: "Тереть",
        eng: "Rub",
        sentenceRus: "Оно едва ли могло быть грязнее, даже если бы он сначала втирал в руки землю и затем ,сильно поплакав, измазал бы свое лицо грязными руками",
        sentenceEng: "It could hardly have been grubbier if he had first rubbed his hands in the earth, and then had a good cry, and then dried his face with his hands",
        audio: null,
    },
    {
        rus: "Главным образом",
        eng: "Сhiefly",
        sentenceRus: "Их приключения начались главным образом благодаря тому, что это было самое мокрое и холодное лето за все последние годы",
        sentenceEng: "Their adventures began chiefly because it was one of the wettest and coldest summers there had been for years.",
        audio: null,
    },

]